version: '3.9'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - api
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: nestjs-docker:0.0.1
    ports:
      - 80:8000
    networks:
      - api
    depends_on:
      - db
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
networks:
  api:
    driver: bridge